name: butler

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types: [created]

jobs:
  chat:
    if: startsWith(github.event.comment.body, '/chat')

    runs-on: ubuntu-latest
    steps:
      - name: Debug comment body
        run: "echo Comment body is: ${{ github.event.comment.body }}"
      - uses: ca-dp/code-butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPEN_API_KEY }}
          cmd: chat
          comment_body: ${{ github.event.comment.body }}