name: cd-azure

on: 
  push:
    paths:
      - ".github/workflows/cd-azure.yml"
      - "EmployeeService (Task4)/EmployeeService/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/setup-buildx-action@v3
      - run: docker buildx ls
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_EMAIL }}
          password: ${{ secrets.DOCKERHUB_PASS }}
      - run: docker build . -t victor435/employeeservice |
          
          docker push victor435/employeeservice
        working-directory: "EmployeeService (Task4)/EmployeeService"
  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build

    steps:
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # - uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: EmployeeService
      #     images: 



