name: cd-on-deploy
on: deployment

jobs:
  send-message:
     runs-on: ubuntu

     steps:
      - name: Post text to a Slack channel
        run: |
          curl -X POST -H 'Content-type: application/json' \
            --data '{"text":"Deployment complete! 
              ${{ toJson(github.event) }}"}' \
            ${{ secrets.SLACK_WEBHOOK_URL }}

