name: cd-on-deploy
on: deployment

jobs:
  send-message:
     runs-on: ubuntu

     steps:
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: Sucessful deployment
            ${{ toJson(github.event) }}

