name: github

on:
  push:
    paths:
      - ".github/workflows/github.yml"
  workflow_dispatch:

jobs:
  cli:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - run: | 
          env
          gh --version
      - uses: actions/checkout@v4
      - run: |
          gh auth status
          gh repo list
          gh workflow list
          gh issue list
          gh api /repos/:owner/:repo/actions/workflows