name: hello

on: workflow_dispatch
  #push:
  #schedule:
  #  - cron: "*/5 * * * *"
  
jobs:
  initial:
  
    runs-on: ubuntu-latest
  
    steps:
      - name: uses checkout workflow
        uses: actions/checkout@v4
    
      - name: print one line
        run: sleep 5

      - name: print multiple lines
        run: echo Print one line, 
             echo Print another line
      

      
    
