name: task1-build

on:
  push:
    paths:
      - ".github/workflows/task1-build.yml"
      - "CalculateAreaLibrary/CalculateAreaLibrary/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: use checkout action
        uses: actions/checkout@v4
      - run: dotnet --list-runtimes
      - run: dotnet --list-sdks
      - run: dotnet build
        working-directory: "./CalculateAreaLibrary (Task 1)/CalculateAreaLibrary"