name: task-build-file

on:
  push:
    paths:
      - ".github/workflows/task-build-file.yml"
      - "CalculateAreaLibrary (Task1)/CalculateAreaLibrary/**"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./CalculateAreaLibrary (Task1)"  

    steps:
      - name: Use checkout action
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.300-preview.0.25177.5"

      - name: Build base project
        run: dotnet build
        working-directory: "./CalculateAreaLibrary (Task1)/CalculateAreaLibrary"

      - name: Build test project
        run: dotnet build
        working-directory: "./CalculateAreaLibrary (Task1)/CalculateAreaTests"
      
      - name: Apply tests
        run: dotnet test
        working-directory: "./CalculateAreaLibrary (Task1)"

      - name: Publish
        run: ../build-xplat.sh
        
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          path: './CalculateAreaLibrary (Task1)/CalculateAreaLibrary/Release'
          name: 'build-${{ matrix.os }}'
        
      