name: task1-build

on:
  push:
    paths:
      - ".github/workflows/task1-build.yml"
      - "CalculateAreaLibrary (Task1)/CalculateAreaLibrary/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./CalculateAreaLibrary (Task1)/CalculateAreaLibrary"  

    steps:
      - name: use checkout action
        uses: actions/checkout@v4

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.300-preview.0.25177.5"

      - run: dotnet build

      - run: dotnet build
        working-directory: "./CalculateAreaLibrary (Task1)/CalculateAreaTests"
      
      - name: apply tests
        run: dotnet test
        working-directory: "./CalculateAreaLibrary (Task1)"
      