name: task-container
defaults:
  run:
    working-directory: './CalculateAreaLibrary (Task1)'

on:
  push:
    paths:
      - ".github/workflows/task-container.yml"
      - "CalculateAreaLibrary (Task1)/CalculateAreaLibrary/**"
  workflow_dispatch:

permissions:
  packages: write

jobs:
  image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: docker version
      - run: docker build . -t calculatearea
      
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker tag calculatearea ghcr.io/VictorCovrig1/InterviewTasks:latest
      - run: docker tag calculatearea ghcr.io/VictorCovrig1/InterviewTasks:${{ github.ref_name }}
      - run: docker push ghcr.io/VictorCovrig1/InterviewTasks:latest
      - run: docker push ghcr.io/VictorCovrig1/InterviewTasks:${{ github.ref_name }}
      
