name: thanks

on:
  issues:
    types: opened

  workflow_dispatch:

jobs:

  print-thanks-message:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:

      - uses: actions/github-script@v7
        id: issue-script

        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          script: |
            const issue_number = context.issue.number || 2;

            console.log(`issue number: ${issue_number}`);

            const { repo, owner } = context.repo;

            // get issue
            const issue = await github.rest.issues.get({
              owner, repo, issue_number
            });

            console.log(`issue: ${issue}`);

            // create comment
            const comment = await github.rest.issues.createComment({
              owner, repo, issue_number,
              body: 'Thanks for your contribution!'
            });

            console.log(`comment data id: {comment.data.id}`);
            console.log(comment.data);

            // add label
            github.rest.issues.addLabels({
              owner, repo, issue_number,
              labels: ['todo-review']
            });

            return comment.data.id;
      
      - run: echo 'comment id=${{ steps.issue-script.outputs.result }}'

      
